FROM jupyter/minimal-notebook:ae5f7e104dd5

LABEL authors="Gustavo Carvalho <carvalho.gustavop@gmail.com>, Joao Pedro Pinheiro <jpinheiro@inf.puc-rio.br>"

RUN conda install -y \
    pandas=0.24.2    \
    xlrd=1.2.0       \
    openpyxl=2.6.1   \
    requests=2.22.0  \
    seaborn=0.9.0    \
    jupyter_contrib_nbextensions=0.5.1
